### ISSUE TITLE
change event not called

### ISSUE THREAD

**Issue by novaknole** [AfikDeri/v-credit-card#11] opened 2019-12-10 11:01 UTC
Thanks for this. Looks like there might be a bug.

`    <VCreditCard ref="creditCard" @change="creditInfoChanged" />
`
   ```
methods: {
    creditInfoChanged(values) {
      console.log("good")
      for (const key in values) {
        this.cardInfo[key] = values[key];
      }

      //validate logic 
      this.validateCard = false;
    },
}
```

The creditInfoChanged function is never called. That's why I put ref and now using this.$refs.creditCard.form to get values when clicked submit button.

Could you look into this?

**Comment by kalitk0** [comment] 2019-12-14 13:53
I have the same issue. Have you found a solution ?

**Comment by AfikDeri** [comment] 2019-12-14 15:48
I just looked into this issue, everything seams to work great. I've created a new vue-cli project, installed the `v-credit-card` package and using the same code as the example in the README file I was able to get this function log values on every change.
Please double check your setup and make sure it's all correct.
If you still have an issue, upload an example project that can reproduce this error and I'll do my best to fix it.

**Comment by AfikDeri** [comment] 2019-12-16 13:13
Closing this issue, can't reproduce..

**Closed by AfikDeri** 2019-12-16 13:13 UTC
